---
apiVersion: v1
data:
  fernet-key: {{ .Files.Get "secrets/fernet_key" | b64enc }}
kind: Secret
metadata:
  name: secret-fernet-key
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  webserver-secret-key: {{ .Files.Get "secrets/webserver_key" | b64enc }}
kind: Secret
metadata:
  name: secret-webserver-key
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  "gitSshKey": {{ .Files.Get "secrets/id_rsa" | b64enc }}
kind: Secret
metadata:
  name: git-sync-ssh-key
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "Opaque"
