---
apiVersion: v1
data:
  tls.crt: {{ .Files.Get "secrets/cacert.pem" | b64enc }}
  tls.key: {{ .Files.Get "secrets/private.pem" | b64enc }}
kind: Secret
metadata:
  name: httpssecret
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: kubernetes.io/tls
---
apiVersion: v1
data:
  connection: {{ .Files.Get "secrets/postgres_uri" | b64enc }}
kind: Secret
metadata:
  name: secret-metadatabase
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  connection: {{ .Files.Get "secrets/celery_uri" | b64enc }}
kind: Secret
metadata:
  name: secret-resultbackend
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  fernet-key: {{ .Files.Get "secrets/fernet_key" | b64enc }}
kind: Secret
metadata:
  name: secret-fernet-key
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  webserver-secret-key: {{ .Files.Get "secrets/webserver_key" | b64enc }}
kind: Secret
metadata:
  name: secret-webserver-key
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
---
apiVersion: v1
data:
  "gitSshKey": {{ .Files.Get "secrets/id_rsa" | b64enc }}
kind: Secret
metadata:
  name: git-secret
  namespace: {{ .Values.cluster.namespace }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: "Opaque"